# TODO: support skip ci (https://github.community/t/github-actions-does-not-respect-skip-ci/17325/8)

name: CI
on:
  workflow_dispatch:

env:
  OCAML_VERSION: 4.14.0

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  windows64-build:
    runs-on: windows-latest
    env:
      PLATFORM: windows64
      ARCH: 64
      MINGW_ARCH: x86_64
      CYG_ROOT: C:\cygwin
    steps:
      - uses: actions/checkout@main
        with:
          submodules: recursive

      - uses: repolevedavaj/install-nsis@v1.1.0
        with:
          nsis-version: '3.10'

      - uses: ./.github/actions/setup-neko

      - uses: ./.github/actions/setup-ocaml-windows

      - name: Set ADD_REVISION=1 for non-release
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        shell: pwsh
        run: echo "ADD_REVISION=1" >> $Env:GITHUB_ENV

      - name: Build Haxe
        shell: pwsh
        run: |
          Set-PSDebug -Trace 1
          $PSNativeCommandUseErrorActionPreference = $true
          $ErrorActionPreference = 'Stop'
          opam exec -- make -s -f Makefile.win -j"$env:NUMBER_OF_PROCESSORS" haxe
          opam exec -- make -s -f Makefile.win haxelib
          opam exec -- make -f Makefile.win echo_package_files package_bin package_installer_win package_choco
          opam exec -- cygcheck ./haxe.exe
          opam exec -- cygcheck ./haxelib.exe
          ls ./out

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: win${{env.ARCH}}Binaries
          path: out


  linux-build:
    strategy:
      matrix:
        arch: [x86_64, arm64]

    runs-on: ${{ matrix.arch == 'x86_64' && 'ubuntu-22.04' || matrix.arch == 'arm64' && 'ubuntu-22.04-arm' ||  matrix.arch == 'armhf' && 'ubuntu-22.04-arm' || 'ubuntu-22.04' }}
    env:
      PLATFORM: linux${{ matrix.arch == 'arm64' && '-arm' || matrix.arch == 'armhf' && '-armhf' || '' }}64
      OPAMYES: 1

    steps:
      - uses: actions/checkout@main
        with:
          submodules: recursive

      - name: Cache opam
        id: cache-opam
        uses: actions/cache@v4
        with:
          path: ~/.opam/
          key: ${{ runner.os }}-${{ matrix.arch }}-${{ env.OCAML_VERSION }}-${{ hashFiles('./haxe.opam', './libs/') }}-1

      - uses: ./.github/actions/setup-neko

      - name: Install dependencies
        run: |
          set -ex
          sudo apt-get update -qqy
          sudo apt-get install -qqy opam libpcre2-dev zlib1g-dev libgtk2.0-dev libmbedtls-dev ninja-build build-essential curl git m4

      - name: Install OCaml libraries
        if: steps.cache-opam.outputs.cache-hit != 'true'
        run: |
          set -ex
          opam init -c ${{ env.OCAML_VERSION }}
          opam pin add haxe . --no-action
          opam install haxe --deps-only --assume-depexts
          opam list
          ocamlopt -v

      - name: Set ADD_REVISION=1 for non-release
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: echo "ADD_REVISION=1" >> $GITHUB_ENV

      - name: Build Haxe
        run: |
          set -ex
          eval $(opam env)
          opam config exec -- make -s -j`nproc` STATICLINK=1 haxe
          opam config exec -- make -s haxelib
          make -s package_unix
          ls -l out
          ldd -v ./haxe || true
          ldd -v ./haxelib || true

      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux${{ matrix.arch == 'arm64' && 'Arm64' || matrix.arch == 'armhf' && 'Arm' || '' }}Binaries
          path: out

      - name: Build xmldoc
        if: matrix.arch == 'x86_64'
        run: |
          set -ex
          make -s xmldoc
          cat >extra/doc/info.json <<EOL
            {
              "commit": "$GITHUB_SHA",
              "branch": "${{ steps.extract_branch.outputs.branch }}"
            }
          EOL

      - name: Upload xmldoc artifact
        if: matrix.arch == 'x86_64'
        uses: actions/upload-artifact@v4
        with:
          name: xmldoc
          path: extra/doc


  mac-build:
    strategy:
      fail-fast: false
      matrix:
        arch: [arm64, x86_64]
    runs-on: macos-latest
    env:
      PLATFORM: mac${{ matrix.arch == 'arm64' && '-arm64' || '' }}
      OPAMYES: 1
      MACOSX_DEPLOYMENT_TARGET: ${{ matrix.arch == 'arm64' && 11.0 || 10.13 }}
    steps:
      - uses: actions/checkout@main
        with:
          submodules: recursive

      - name: Cache opam
        id: cache-opam
        uses: actions/cache@v4
        with:
          path: ~/.opam/
          key: macos-${{ matrix.arch }}-${{ env.OCAML_VERSION }}-${{ hashFiles('./haxe.opam', './libs/') }}-1

      - uses: ./.github/actions/setup-neko

      - name: Install dependencies
        env:
          ZLIB_VERSION: 1.3.1
          MBEDTLS_VERSION: 3.6.4
          PCRE2_VERSION: 10.45
          CMAKE_BUILD_TYPE: Release
          CMAKE_GENERATOR: Ninja
        run: |
          set -ex
          brew update
          brew bundle --file=tests/Brewfile --no-upgrade

      - name: Install Opam
        run: |
          curl -sSL https://github.com/ocaml/opam/releases/download/2.3.0/opam-2.3.0-${{ matrix.arch }}-macos -o $RUNNER_TEMP/opam
          sudo install $RUNNER_TEMP/opam /usr/local/bin/opam

      - name: Install OCaml libraries
        if: steps.cache-opam.outputs.cache-hit != 'true'
        run: |
          set -ex
          opam init -c ${{ env.OCAML_VERSION }}
          opam update
          eval $(opam env)
          opam pin add haxe . --no-action
          opam install haxe --deps-only --assume-depexts

      - name: Set ADD_REVISION=1 for non-release
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: echo "ADD_REVISION=1" >> $GITHUB_ENV

      - name: Build Haxe
        run: |
          set -ex
          eval $(opam env)
          opam exec -- make -s STATICLINK=1 haxe
          opam exec -- make -s haxelib
          opam exec -- make -s package_unix package_installer_mac
          ls -l out

      - name: Upload artifact (x64)
        if: matrix.arch == 'x86_64'
        uses: actions/upload-artifact@v4
        with:
          name: macX64Binaries
          path: out

      - name: Upload artifact (arm)
        if: matrix.arch == 'arm64'
        uses: actions/upload-artifact@v4
        with:
          name: macArmBinaries
          path: out


  mac-build-universal:
    needs: mac-build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main

      - uses: actions/download-artifact@v4
        with:
          name: macX64Binaries
          path: macX64Binaries

      - uses: actions/download-artifact@v4
        with:
          name: macArmBinaries
          path: macArmBinaries

      - name: Make universal binary
        run: |
          set -ex
          tar -xf macX64Binaries/*_bin.tar.gz -C macX64Binaries --strip-components=1
          tar -xf macArmBinaries/*_bin.tar.gz -C macArmBinaries --strip-components=1
          lipo -create -output haxe macX64Binaries/haxe macArmBinaries/haxe
          lipo -create -output haxelib macX64Binaries/haxelib macArmBinaries/haxelib
          make -s package_unix package_installer_mac PACKAGE_INSTALLER_MAC_ARCH=universal
          ls -l out

      - name: Upload artifact (universal)
        uses: actions/upload-artifact@v4
        with:
          name: macBinaries
          path: out
